# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"
BBFILE_PATTERN_altera-platform := "^${LAYERDIR}/"

BBFILES:append = " ${LAYERDIR}/recipes-images/*/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-connectivity/linuxptp/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-connectivity/open62541/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-connectivity/tsn-ref-sw/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-connectivity/xdp-tools/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-core/*/*.bbappend"
BBFILES:append = " ${LAYERDIR}/recipes-devtools/*/*.bbappend"
BBFILES:append = " ${LAYERDIR}/recipes-benchmarking/*/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-apps/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-initscripts/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-intel-fcs-lib/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-lighttpd-conf/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-pio-interrupt/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-unilibrsu-lib/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/remote-debug-app/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/gsrd-webcontent/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-gsrd/libarchive/libarchive_%.bbappend"

BBFILE_COLLECTIONS += "altera-platform"
BBFILE_PATTERN_altera-platform = "^${LAYERDIR}/"
BBFILE_PRIORITY_altera-platform = "5"

LAYERSERIES_COMPAT_altera-platform = "main styhead walnascar"

BBDEBUG = "yes"

