# Disable mutual TLS authentication for agilex3.
#
# meta-phosphor enables mutual-tls-auth by default in its PACKAGECONFIG.
# Mutual TLS requires the browser/client to present a client certificate in
# addition to the server's certificate — this is not set up on the Agilex3
# development board and causes all HTTPS connections to be rejected with a
# TLS handshake error.
#
# For the Agilex3 BMC, standard username/password authentication via HTTPS
# is sufficient. The server-side TLS certificate (generated by
# phosphor-certificate-manager@bmcweb.service on first boot) is still used,
# so the HTTPS transport is encrypted. Only the mTLS client-certificate
# requirement is removed.
PACKAGECONFIG:remove = "mutual-tls-auth"

# Use the known-good bmcweb commit from git.ami.com that runs correctly on
# AArch64/Agilex3.  The AMI OCP GitHub fork commit (b76407e4) causes a
# SIGSEGV on startup on Agilex3 (confirmed via coredump). This matches
# the commit used by the working Agilex5 OT reference build.
# Note: the same approach is used in the Agilex5 OT meta-ami bbappend.
SRC_URI = "git://git.ami.com/core/ami-bmc/one-tree/core/bmcweb;branch=master;protocol=https;name=override;"
SRCREV_override = "e56730cf2bfdb21ae5bc51b3774f8693fd9297c4"

# Install a systemd drop-in that orders bmcweb.service AFTER
# phosphor-certificate-manager@bmcweb.service so that the TLS server
# certificate is guaranteed to exist before bmcweb tries to load it.
# Without this, bmcweb races the cert generator on first boot, crashes
# (SIGSEGV in ssl::context::use_certificate_file), hits the restart
# rate-limit, and the web UI stays permanently unavailable.
FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

SRC_URI:append = " \
    file://bmcweb.service.d/10-cert-dependency.conf \
"

do_install:append() {
    install -d ${D}${systemd_system_unitdir}/bmcweb.service.d
    install -m 0644 ${UNPACKDIR}/bmcweb.service.d/10-cert-dependency.conf \
        ${D}${systemd_system_unitdir}/bmcweb.service.d/10-cert-dependency.conf
}

FILES:${PN} += "${systemd_system_unitdir}/bmcweb.service.d/10-cert-dependency.conf"
