# Disable mutual TLS authentication for agilex3.
#
# meta-phosphor enables mutual-tls-auth by default in its PACKAGECONFIG.
# Mutual TLS requires the browser/client to present a client certificate in
# addition to the server's certificate — this is not set up on the Agilex3
# development board and causes all HTTPS connections to be rejected with a
# TLS handshake error.
#
# For the Agilex3 BMC, standard username/password authentication via HTTPS
# is sufficient. The server-side TLS certificate (generated by
# phosphor-certificate-manager@bmcweb.service on first boot) is still used,
# so the HTTPS transport is encrypted. Only the mTLS client-certificate
# requirement is removed.
PACKAGECONFIG:remove = "mutual-tls-auth"

# Install a systemd drop-in that orders bmcweb.service AFTER
# phosphor-certificate-manager@bmcweb.service so that the TLS server
# certificate is guaranteed to exist before bmcweb tries to load it.
# Without this, bmcweb races the cert generator on first boot, crashes
# (SIGSEGV in ssl::context::use_certificate_file), hits the restart
# rate-limit, and the web UI stays permanently unavailable.
FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

SRC_URI:append = " \
    file://bmcweb.service.d/10-cert-dependency.conf \
"

do_install:append() {
    install -d ${D}${systemd_system_unitdir}/bmcweb.service.d
    install -m 0644 ${UNPACKDIR}/bmcweb.service.d/10-cert-dependency.conf \
        ${D}${systemd_system_unitdir}/bmcweb.service.d/10-cert-dependency.conf
}

FILES:${PN} += "${systemd_system_unitdir}/bmcweb.service.d/10-cert-dependency.conf"
