# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "altera-bsp"
BBFILE_PATTERN_altera-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_altera-bsp = "5"

# LAYERDEPENDS_altera-bsp = ""
LAYERSERIES_COMPAT_altera-bsp = "main styhead scarthgap walnascar"

BBDEBUG = "yes"
