# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend"

BBFILE_COLLECTIONS += "altera-common"
BBFILE_PATTERN_altera-common = "^${LAYERDIR}/"
BBFILE_PRIORITY_altera-common = "7"

# Shared recipes common to all Altera SoCFPGA OpenBMC machine layers
# (meta-agilex3, meta-agilex5, etc.)
LAYERDEPENDS_altera-common = "phosphor-layer altera-layer altera-bsp meta-ami common"

LAYERSERIES_COMPAT_altera-common = "walnascar"
